-- ============================================================================
-- VWB LayoutConfig - the APP SHELL, as DATA (box model v2)
-- ============================================================================
-- The persistent chrome ABOVE any single view: a sidebar nav on the left, a
-- content region where the ACTIVE VIEW mounts, and a status bar along the
-- bottom. The window supplies its own title bar; the shell owns everything
-- below it. The nav rows + the views are generated by the Shell controller
-- from the view registry (not hard-coded here) and mounted into the `sidebar`
-- and `content` cells. This is the "each slot is itself a layout" recursion,
-- one level up from a view.
--
--   +---------+------------------------------------------------+
--   | sidebar |  content  (active view mounts here)            |
--   |  (nav)  |                                                |
--   +---------+------------------------------------------------+
--   | status bar (full width)                                  |
--   +----------------------------------------------------------+
-- ============================================================================

local _, ns = ...
ns = ns or {}
ns.LayoutConfig = ns.LayoutConfig or {}

ns.LayoutConfig.shell = {
    type = "grid",
    padding = 0,
    gap = 0,
    columns = { 160, "flex" }, -- sidebar | content (150 -> 160 for nav row icons, 2026-07-13)
    rows    = { "flex", 22 },  -- body | status bar
    cells = {
        { at = { col = 1, row = 1 }, child = { type = "item", id = "sidebar" } },
        { at = { col = 2, row = 1 }, child = { type = "item", id = "content" } },
        { at = { col = 1, row = 2, colSpan = 2 }, child = { type = "item", id = "status" } },
    },
}

return ns.LayoutConfig
